"""describe your changes here

Revision ID: 7bbab3d76cf7
Revises: 241a307d2709
Create Date: 2026-09-11 13:59:25.941191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7bbab3d76cf7'
down_revision: Union[str, Sequence[str], None] = '241a307d2709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('product', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_product_username'), table_name='product')
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=True)
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    op.drop_column('product', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('username', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.create_index(op.f('ix_product_username'), 'product', ['username'], unique=True)
    op.drop_column('product', 'category_id')
    op.drop_column('product', 'price')
    op.drop_column('product', 'name')
    # ### end Alembic commands ###
